Repository OCA/stock-logistics-request, pull requests merged in 2024-06, with the labels that each got.

#25 [17.0][FIX] stock_request: avoid failure on handling errors
  stock_request/models/stock_request.py
Labels: approved, ready to merge, bot is merging ⏳

#26 [17.0][MIG] stock_request_mrp
  stock_request_mrp/README.rst
  stock_request_mrp/__init__.py
  stock_request_mrp/__manifest__.py
  stock_request_mrp/hooks.py
  stock_request_mrp/i18n/es.po
  stock_request_mrp/i18n/it.po
  stock_request_mrp/i18n/stock_request_mrp.pot
  stock_request_mrp/models/__init__.py
  stock_request_mrp/models/mrp_production.py
  stock_request_mrp/models/stock_request.py
  stock_request_mrp/models/stock_request_order.py
  stock_request_mrp/models/stock_rule.py
  stock_request_mrp/pyproject.toml
  stock_request_mrp/readme/CONTRIBUTORS.md
  stock_request_mrp/readme/DESCRIPTION.md
  stock_request_mrp/readme/ROADMAP.md
  stock_request_mrp/readme/USAGE.md
  stock_request_mrp/security/ir.model.access.csv
  stock_request_mrp/static/description/icon.png
  stock_request_mrp/static/description/index.html
  stock_request_mrp/tests/__init__.py
  stock_request_mrp/tests/test_stock_request_mrp.py
  stock_request_mrp/views/mrp_production_views.xml
  stock_request_mrp/views/stock_request_order_views.xml
  stock_request_mrp/views/stock_request_views.xml
Labels: bot is merging ⏳

#32 [17.0][MIG] stock_request_stage
  stock_request_stage/README.rst
  stock_request_stage/__init__.py
  stock_request_stage/__manifest__.py
  stock_request_stage/models/__init__.py
  stock_request_stage/models/stock_request.py
  stock_request_stage/models/stock_request_stage.py
  stock_request_stage/pyproject.toml
  stock_request_stage/readme/CONFIGURE.md
  stock_request_stage/readme/CONTRIBUTORS.md
  stock_request_stage/readme/DESCRIPTION.md
  stock_request_stage/readme/USAGE.md
  stock_request_stage/security/ir.model.access.csv
  stock_request_stage/static/description/index.html
  stock_request_stage/views/stock_request_menu.xml
  stock_request_stage/views/stock_request_stage_views.xml
  stock_request_stage/views/stock_request_views.xml
Labels: approved, migration, needs review, bot is merging ⏳

#20 [16.0][MIG] stock_request_direction: Migration to 16.0
  setup/stock_request_direction/odoo/addons/stock_request_direction
  setup/stock_request_direction/setup.py
  stock_request_direction/README.rst
  stock_request_direction/__init__.py
  stock_request_direction/__manifest__.py
  stock_request_direction/i18n/es.po
  stock_request_direction/i18n/it.po
  stock_request_direction/i18n/stock_request_direction.pot
  stock_request_direction/i18n/zh_CN.po
  stock_request_direction/models/__init__.py
  stock_request_direction/models/stock_request.py
  stock_request_direction/models/stock_request_order.py
  stock_request_direction/readme/CONTRIBUTORS.rst
  stock_request_direction/readme/DESCRIPTION.rst
  stock_request_direction/readme/USAGE.rst
  stock_request_direction/static/description/icon.png
  stock_request_direction/static/description/index.html
  stock_request_direction/tests/__init__.py
  stock_request_direction/tests/test_stock_request_direction.py
  stock_request_direction/views/res_config_settings.xml
  stock_request_direction/views/stock_request_order_views.xml
  stock_request_direction/views/stock_request_views.xml
Labels: approved, migration, ready to merge, needs review, bot is merging ⏳

#33 [17.0][MIG] stock_request_direction: Migration to 17.0
  stock_request_direction/README.rst
  stock_request_direction/__init__.py
  stock_request_direction/__manifest__.py
  stock_request_direction/i18n/es.po
  stock_request_direction/i18n/it.po
  stock_request_direction/i18n/stock_request_direction.pot
  stock_request_direction/i18n/zh_CN.po
  stock_request_direction/models/__init__.py
  stock_request_direction/models/stock_request.py
  stock_request_direction/models/stock_request_order.py
  stock_request_direction/pyproject.toml
  stock_request_direction/readme/CONTRIBUTORS.md
  stock_request_direction/readme/DESCRIPTION.md
  stock_request_direction/readme/USAGE.md
  stock_request_direction/static/description/icon.png
  stock_request_direction/static/description/index.html
  stock_request_direction/tests/__init__.py
  stock_request_direction/tests/test_stock_request_direction.py
  stock_request_direction/views/res_config_settings.xml
  stock_request_direction/views/stock_request_order_views.xml
  stock_request_direction/views/stock_request_views.xml
Labels: approved, bot is merging ⏳

#21 [16.0][MIG] stock_request_picking_type: Migration to 16.0
  setup/stock_request_picking_type/odoo/addons/stock_request_picking_type
  setup/stock_request_picking_type/setup.py
  stock_request_picking_type/README.rst
  stock_request_picking_type/__init__.py
  stock_request_picking_type/__manifest__.py
  stock_request_picking_type/data/stock_picking_type.xml
  stock_request_picking_type/i18n/es.po
  stock_request_picking_type/i18n/it.po
  stock_request_picking_type/i18n/pt_BR.po
  stock_request_picking_type/i18n/stock_request_picking_type.pot
  stock_request_picking_type/i18n/zh_CN.po
  stock_request_picking_type/models/__init__.py
  stock_request_picking_type/models/stock_picking_type.py
  stock_request_picking_type/models/stock_request_order.py
  stock_request_picking_type/readme/CONTRIBUTORS.rst
  stock_request_picking_type/readme/DESCRIPTION.rst
  stock_request_picking_type/readme/USAGE.rst
  stock_request_picking_type/static/description/icon.png
  stock_request_picking_type/static/description/index.html
  stock_request_picking_type/tests/__init__.py
  stock_request_picking_type/tests/test_stock_picking_type.py
  stock_request_picking_type/tests/test_stock_request.py
  stock_request_picking_type/views/stock_picking_views.xml
  stock_request_picking_type/views/stock_request_order_views.xml
Labels: approved, migration, ready to merge, needs review, bot is merging ⏳
