Repository OCA/stock-logistics-request, pull requests merged in 2024-09, with the labels that each got.

#31 [17.0][MIG] stock_request_kanban
  stock_request_kanban/README.rst
  stock_request_kanban/__init__.py
  stock_request_kanban/__manifest__.py
  stock_request_kanban/data/stock_request_sequence_data.xml
  stock_request_kanban/i18n/es.po
  stock_request_kanban/i18n/stock_request_kanban.pot
  stock_request_kanban/i18n/zh_CN.po
  stock_request_kanban/models/__init__.py
  stock_request_kanban/models/product.py
  stock_request_kanban/models/stock_inventory_kanban.py
  stock_request_kanban/models/stock_request.py
  stock_request_kanban/models/stock_request_kanban.py
  stock_request_kanban/pyproject.toml
  stock_request_kanban/readme/CONFIGURE.md
  stock_request_kanban/readme/CONTRIBUTORS.md
  stock_request_kanban/readme/DESCRIPTION.md
  stock_request_kanban/readme/USAGE.md
  stock_request_kanban/report/report_paper_format.xml
  stock_request_kanban/report/stock_request_kanban_templates.xml
  stock_request_kanban/security/ir.model.access.csv
  stock_request_kanban/static/description/icon.png
  stock_request_kanban/static/description/index.html
  stock_request_kanban/tests/__init__.py
  stock_request_kanban/tests/base_test.py
  stock_request_kanban/tests/test_inventory_kanban.py
  stock_request_kanban/tests/test_kanban.py
  stock_request_kanban/views/product_views.xml
  stock_request_kanban/views/stock_inventory_kanban_views.xml
  stock_request_kanban/views/stock_request_kanban_views.xml
  stock_request_kanban/views/stock_request_menu.xml
  stock_request_kanban/views/stock_request_order_views.xml
  stock_request_kanban/views/stock_request_views.xml
  stock_request_kanban/wizard/__init__.py
  stock_request_kanban/wizard/wizard_stock_inventory_kanban.py
  stock_request_kanban/wizard/wizard_stock_inventory_kanban_views.xml
  stock_request_kanban/wizard/wizard_stock_request_kanban.py
  stock_request_kanban/wizard/wizard_stock_request_kanban_abstract.py
  stock_request_kanban/wizard/wizard_stock_request_kanban_views.xml
  stock_request_kanban/wizard/wizard_stock_request_order_kanban.py
  stock_request_kanban/wizard/wizard_stock_request_order_kanban_views.xml
Labels: bot is merging ⏳

#40 [16.0][IMP] stock_request: Improve _check_qty constrain (moved to stock.request)
  stock_request/models/stock_request.py
  stock_request/models/stock_request_abstract.py
  stock_request_purchase/models/stock_request.py
Labels: approved, bot is merging ⏳

#41 [16.0][IMP] stock_request_purchase: Cancel stock request when unlinking related purchase order lines
  stock_request_purchase/models/purchase_order_line.py
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: enhancement, approved, bot is merging ⏳

#42 [17.0][IMP] stock_request_purchase: Cancel stock request when unlinking related purchase order lines
  stock_request_purchase/models/purchase_order_line.py
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: approved, bot is merging ⏳

#43 [17.0][IMP] stock_request: Improve _check_qty constrain (moved to stock.request)
  stock_request/models/stock_request.py
  stock_request/models/stock_request_abstract.py
  stock_request_purchase/models/stock_request.py
Labels: approved, bot is merging ⏳
