Repository OCA/stock-logistics-request, pull requests merged in 2025-04, with the labels that each got.

#56 [18.0][MIG] stock_return_request: Migration to version 18.0
  stock_request_mrp/tests/test_stock_request_mrp.py
  stock_return_request/README.rst
  stock_return_request/__init__.py
  stock_return_request/__manifest__.py
  stock_return_request/data/stock_return_request_data.xml
  stock_return_request/i18n/es.po
  stock_return_request/i18n/fr.po
  stock_return_request/i18n/it.po
  stock_return_request/i18n/pt_BR.po
  stock_return_request/i18n/pt_PT.po
  stock_return_request/i18n/stock_return_request.pot
  stock_return_request/models/__init__.py
  stock_return_request/models/stock_move.py
  stock_return_request/models/stock_picking.py
  stock_return_request/models/stock_return_request.py
  stock_return_request/pyproject.toml
  stock_return_request/readme/CONTRIBUTORS.md
  stock_return_request/readme/DESCRIPTION.md
  stock_return_request/readme/INSTALL.md
  stock_return_request/readme/ROADMAP.md
  stock_return_request/readme/USAGE.md
  stock_return_request/report/stock_return_report.xml
  stock_return_request/security/ir.model.access.csv
  stock_return_request/static/description/icon.png
  stock_return_request/static/description/index.html
  stock_return_request/tests/__init__.py
  stock_return_request/tests/test_stock_return_request.py
  stock_return_request/tests/test_stock_return_request_common.py
  stock_return_request/views/stock_return_request_views.xml
  stock_return_request/wizard/__init__.py
  stock_return_request/wizard/suggest_return_request.xml
  stock_return_request/wizard/suggest_return_request_lot.py
Labels: approved, migration, needs review, bot is merging ⏳

#63 [17.0][IMP] stock_request: Add config to enable/disable requested_by check
  stock_request/README.rst
  stock_request/models/res_company.py
  stock_request/models/res_config_settings.py
  stock_request/models/stock_request.py
  stock_request/readme/CONTRIBUTORS.md
  stock_request/static/description/index.html
  stock_request/tests/test_stock_request.py
  stock_request/views/res_config_settings_views.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#64 [18.0][FIX] stock_request: improve UI (state, confirm button and Config setting)
  stock_request/tests/test_stock_request.py
  stock_request/views/res_config_settings_views.xml
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
Labels: approved, bot is merging ⏳
