Repository OCA/stock-logistics-request, pull requests merged in 2025-03, with the labels that each got.

#60 [17.0][IMP] stock_request_kanban: create multi
  stock_request_kanban/models/stock_inventory_kanban.py
  stock_request_kanban/models/stock_request_kanban.py
Labels: approved, bot is merging ⏳

#51 [18.0][MIG] stock_request_purchase: Migration to 18.0
  stock_request_purchase/README.rst
  stock_request_purchase/__init__.py
  stock_request_purchase/__manifest__.py
  stock_request_purchase/i18n/de.po
  stock_request_purchase/i18n/es.po
  stock_request_purchase/i18n/it.po
  stock_request_purchase/i18n/stock_request_purchase.pot
  stock_request_purchase/i18n/zh_CN.po
  stock_request_purchase/models/__init__.py
  stock_request_purchase/models/purchase_order.py
  stock_request_purchase/models/purchase_order_line.py
  stock_request_purchase/models/stock_request.py
  stock_request_purchase/models/stock_request_order.py
  stock_request_purchase/models/stock_rule.py
  stock_request_purchase/pyproject.toml
  stock_request_purchase/readme/CONTRIBUTORS.md
  stock_request_purchase/readme/DESCRIPTION.md
  stock_request_purchase/readme/ROADMAP.md
  stock_request_purchase/readme/USAGE.md
  stock_request_purchase/security/ir.model.access.csv
  stock_request_purchase/static/description/icon.png
  stock_request_purchase/static/description/index.html
  stock_request_purchase/tests/__init__.py
  stock_request_purchase/tests/test_stock_request_purchase.py
  stock_request_purchase/views/purchase_order_views.xml
  stock_request_purchase/views/stock_request_order_views.xml
  stock_request_purchase/views/stock_request_views.xml
Labels: migration, needs review, bot is merging ⏳

#52 [18.0][MIG] stock_request_mrp: Migration to 18.0
  stock_request_mrp/README.rst
  stock_request_mrp/__init__.py
  stock_request_mrp/__manifest__.py
  stock_request_mrp/hooks.py
  stock_request_mrp/i18n/es.po
  stock_request_mrp/i18n/it.po
  stock_request_mrp/i18n/stock_request_mrp.pot
  stock_request_mrp/models/__init__.py
  stock_request_mrp/models/mrp_production.py
  stock_request_mrp/models/stock_request.py
  stock_request_mrp/models/stock_request_order.py
  stock_request_mrp/models/stock_rule.py
  stock_request_mrp/pyproject.toml
  stock_request_mrp/readme/CONTRIBUTORS.md
  stock_request_mrp/readme/DESCRIPTION.md
  stock_request_mrp/readme/ROADMAP.md
  stock_request_mrp/readme/USAGE.md
  stock_request_mrp/security/ir.model.access.csv
  stock_request_mrp/static/description/icon.png
  stock_request_mrp/static/description/index.html
  stock_request_mrp/tests/__init__.py
  stock_request_mrp/tests/test_stock_request_mrp.py
  stock_request_mrp/views/mrp_production_views.xml
  stock_request_mrp/views/stock_request_order_views.xml
  stock_request_mrp/views/stock_request_views.xml
Labels: approved, migration, needs review, bot is merging ⏳
